GET http://localhost:3333/courses

###

POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Docker Cours",
    "description": "Course for software engineers"
}

###

GET http://localhost:3333/courses/5ef34ffb-b15e-4aee-bd8c-c4b54c0a91bc

